FROM golang:1.23.5-bookworm

WORKDIR /app

RUN go install github.com/air-verse/air@latest

COPY ./golang/go.mod ./golang/go.sum ./

RUN go mod download && go mod verify

EXPOSE 3333

CMD ["air", "-c", ".air.toml"]